// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: api/proto/v1/agent.proto

package bmcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel_Level int32

const (
	LogLevel_LEVEL_UNSPECIFIED LogLevel_Level = 0
	LogLevel_DEBUG             LogLevel_Level = 1
	LogLevel_INFO              LogLevel_Level = 2
	LogLevel_WARN              LogLevel_Level = 3
	LogLevel_ERROR             LogLevel_Level = 4
)

// Enum value maps for LogLevel_Level.
var (
	LogLevel_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "DEBUG",
		2: "INFO",
		3: "WARN",
		4: "ERROR",
	}
	LogLevel_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"DEBUG":             1,
		"INFO":              2,
		"WARN":              3,
		"ERROR":             4,
	}
)

func (x LogLevel_Level) Enum() *LogLevel_Level {
	p := new(LogLevel_Level)
	*p = x
	return p
}

func (x LogLevel_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_agent_proto_enumTypes[0].Descriptor()
}

func (LogLevel_Level) Type() protoreflect.EnumType {
	return &file_api_proto_v1_agent_proto_enumTypes[0]
}

func (x LogLevel_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel_Level.Descriptor instead.
func (LogLevel_Level) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{9, 0}
}

type RunResult_Status int32

const (
	RunResult_STATUS_UNSPECIFIED RunResult_Status = 0
	RunResult_SUCCEEDED          RunResult_Status = 1
	RunResult_FAILED             RunResult_Status = 2
	RunResult_CANCELLED          RunResult_Status = 3
)

// Enum value maps for RunResult_Status.
var (
	RunResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "SUCCEEDED",
		2: "FAILED",
		3: "CANCELLED",
	}
	RunResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"SUCCEEDED":          1,
		"FAILED":             2,
		"CANCELLED":          3,
	}
)

func (x RunResult_Status) Enum() *RunResult_Status {
	p := new(RunResult_Status)
	*p = x
	return p
}

func (x RunResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_agent_proto_enumTypes[1].Descriptor()
}

func (RunResult_Status) Type() protoreflect.EnumType {
	return &file_api_proto_v1_agent_proto_enumTypes[1]
}

func (x RunResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunResult_Status.Descriptor instead.
func (RunResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{12, 0}
}

type ExecuteCommand_Operation int32

const (
	ExecuteCommand_OPERATION_UNSPECIFIED ExecuteCommand_Operation = 0
	ExecuteCommand_BACKUP                ExecuteCommand_Operation = 1
	ExecuteCommand_RESTORE               ExecuteCommand_Operation = 2
	ExecuteCommand_RESTORE_DRY_RUN       ExecuteCommand_Operation = 3
	ExecuteCommand_CHECK                 ExecuteCommand_Operation = 4
	ExecuteCommand_FORGET                ExecuteCommand_Operation = 5
	ExecuteCommand_SNAPSHOTS             ExecuteCommand_Operation = 6
	ExecuteCommand_SNAPSHOT_LS           ExecuteCommand_Operation = 7
	ExecuteCommand_VERIFY_STORAGE_REMOTE ExecuteCommand_Operation = 8
	ExecuteCommand_VALIDATE_PATHS        ExecuteCommand_Operation = 9
	ExecuteCommand_PROBE_CAPABILITIES    ExecuteCommand_Operation = 10
)

// Enum value maps for ExecuteCommand_Operation.
var (
	ExecuteCommand_Operation_name = map[int32]string{
		0:  "OPERATION_UNSPECIFIED",
		1:  "BACKUP",
		2:  "RESTORE",
		3:  "RESTORE_DRY_RUN",
		4:  "CHECK",
		5:  "FORGET",
		6:  "SNAPSHOTS",
		7:  "SNAPSHOT_LS",
		8:  "VERIFY_STORAGE_REMOTE",
		9:  "VALIDATE_PATHS",
		10: "PROBE_CAPABILITIES",
	}
	ExecuteCommand_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"BACKUP":                1,
		"RESTORE":               2,
		"RESTORE_DRY_RUN":       3,
		"CHECK":                 4,
		"FORGET":                5,
		"SNAPSHOTS":             6,
		"SNAPSHOT_LS":           7,
		"VERIFY_STORAGE_REMOTE": 8,
		"VALIDATE_PATHS":        9,
		"PROBE_CAPABILITIES":    10,
	}
)

func (x ExecuteCommand_Operation) Enum() *ExecuteCommand_Operation {
	p := new(ExecuteCommand_Operation)
	*p = x
	return p
}

func (x ExecuteCommand_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteCommand_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_agent_proto_enumTypes[2].Descriptor()
}

func (ExecuteCommand_Operation) Type() protoreflect.EnumType {
	return &file_api_proto_v1_agent_proto_enumTypes[2]
}

func (x ExecuteCommand_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteCommand_Operation.Descriptor instead.
func (ExecuteCommand_Operation) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{16, 0}
}

type EnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os              string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch            string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Version         string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Exactly 32 random bytes generated by the agent at first boot.
	Secret []byte `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	// Optional: when non-empty, requests re-enrollment/takeover of an existing agent ID.
	TargetAgentId string `protobuf:"bytes,7,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnrollRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *EnrollRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EnrollRequest) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *EnrollRequest) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_CommandAccepted
	//	*AgentMessage_RunProgress
	//	*AgentMessage_RunLogBatch
	//	*AgentMessage_RunResult
	//	*AgentMessage_CapabilitiesReport
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandAccepted() *CommandAccepted {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandAccepted); ok {
			return x.CommandAccepted
		}
	}
	return nil
}

func (x *AgentMessage) GetRunProgress() *RunProgress {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RunProgress); ok {
			return x.RunProgress
		}
	}
	return nil
}

func (x *AgentMessage) GetRunLogBatch() *RunLogBatch {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RunLogBatch); ok {
			return x.RunLogBatch
		}
	}
	return nil
}

func (x *AgentMessage) GetRunResult() *RunResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RunResult); ok {
			return x.RunResult
		}
	}
	return nil
}

func (x *AgentMessage) GetCapabilitiesReport() *CapabilitiesReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CapabilitiesReport); ok {
			return x.CapabilitiesReport
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_CommandAccepted struct {
	CommandAccepted *CommandAccepted `protobuf:"bytes,12,opt,name=command_accepted,json=commandAccepted,proto3,oneof"`
}

type AgentMessage_RunProgress struct {
	RunProgress *RunProgress `protobuf:"bytes,13,opt,name=run_progress,json=runProgress,proto3,oneof"`
}

type AgentMessage_RunLogBatch struct {
	RunLogBatch *RunLogBatch `protobuf:"bytes,14,opt,name=run_log_batch,json=runLogBatch,proto3,oneof"`
}

type AgentMessage_RunResult struct {
	RunResult *RunResult `protobuf:"bytes,15,opt,name=run_result,json=runResult,proto3,oneof"`
}

type AgentMessage_CapabilitiesReport struct {
	CapabilitiesReport *CapabilitiesReport `protobuf:"bytes,16,opt,name=capabilities_report,json=capabilitiesReport,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_CommandAccepted) isAgentMessage_Payload() {}

func (*AgentMessage_RunProgress) isAgentMessage_Payload() {}

func (*AgentMessage_RunLogBatch) isAgentMessage_Payload() {}

func (*AgentMessage_RunResult) isAgentMessage_Payload() {}

func (*AgentMessage_CapabilitiesReport) isAgentMessage_Payload() {}

type ServerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Welcome
	//	*ServerMessage_ExecuteCommand
	//	*ServerMessage_CancelCommand
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerMessage) GetExecuteCommand() *ExecuteCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecuteCommand); ok {
			return x.ExecuteCommand
		}
	}
	return nil
}

func (x *ServerMessage) GetCancelCommand() *CancelCommand {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CancelCommand); ok {
			return x.CancelCommand
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,10,opt,name=welcome,proto3,oneof"`
}

type ServerMessage_ExecuteCommand struct {
	ExecuteCommand *ExecuteCommand `protobuf:"bytes,11,opt,name=execute_command,json=executeCommand,proto3,oneof"`
}

type ServerMessage_CancelCommand struct {
	CancelCommand *CancelCommand `protobuf:"bytes,12,opt,name=cancel_command,json=cancelCommand,proto3,oneof"`
}

func (*ServerMessage_Welcome) isServerMessage_Payload() {}

func (*ServerMessage_ExecuteCommand) isServerMessage_Payload() {}

func (*ServerMessage_CancelCommand) isServerMessage_Payload() {}

// Hello must be the first message on every Connect stream.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Welcome struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion            string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ServerInstanceId         string                 `protobuf:"bytes,2,opt,name=server_instance_id,json=serverInstanceId,proto3" json:"server_instance_id,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	// True when agent/server minor versions differ (connection allowed, UI warns).
	VersionMinorMismatch bool `protobuf:"varint,4,opt,name=version_minor_mismatch,json=versionMinorMismatch,proto3" json:"version_minor_mismatch,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Welcome) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *Welcome) GetServerInstanceId() string {
	if x != nil {
		return x.ServerInstanceId
	}
	return ""
}

func (x *Welcome) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *Welcome) GetVersionMinorMismatch() bool {
	if x != nil {
		return x.VersionMinorMismatch
	}
	return false
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixNanos     int64                  `protobuf:"varint,1,opt,name=unix_nanos,json=unixNanos,proto3" json:"unix_nanos,omitempty"`
	UptimeSeconds float64                `protobuf:"fixed64,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetUnixNanos() int64 {
	if x != nil {
		return x.UnixNanos
	}
	return 0
}

func (x *Heartbeat) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// Acknowledge receipt of an ExecuteCommand before execution starts.
type CommandAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAccepted) Reset() {
	*x = CommandAccepted{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAccepted) ProtoMessage() {}

func (x *CommandAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAccepted.ProtoReflect.Descriptor instead.
func (*CommandAccepted) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *CommandAccepted) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAccepted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RunProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	BytesDone     int64                  `protobuf:"varint,4,opt,name=bytes_done,json=bytesDone,proto3" json:"bytes_done,omitempty"`
	BytesTotal    int64                  `protobuf:"varint,5,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	FilesDone     int64                  `protobuf:"varint,6,opt,name=files_done,json=filesDone,proto3" json:"files_done,omitempty"`
	FilesTotal    int64                  `protobuf:"varint,7,opt,name=files_total,json=filesTotal,proto3" json:"files_total,omitempty"`
	DetailJson    string                 `protobuf:"bytes,8,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunProgress) Reset() {
	*x = RunProgress{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunProgress) ProtoMessage() {}

func (x *RunProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunProgress.ProtoReflect.Descriptor instead.
func (*RunProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RunProgress) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RunProgress) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *RunProgress) GetBytesDone() int64 {
	if x != nil {
		return x.BytesDone
	}
	return 0
}

func (x *RunProgress) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *RunProgress) GetFilesDone() int64 {
	if x != nil {
		return x.FilesDone
	}
	return 0
}

func (x *RunProgress) GetFilesTotal() int64 {
	if x != nil {
		return x.FilesTotal
	}
	return 0
}

func (x *RunProgress) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

type LogLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel_Level         `protobuf:"varint,1,opt,name=level,proto3,enum=bmc.v1.LogLevel_Level" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevel) Reset() {
	*x = LogLevel{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevel) ProtoMessage() {}

func (x *LogLevel) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevel.ProtoReflect.Descriptor instead.
func (*LogLevel) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *LogLevel) GetLevel() LogLevel_Level {
	if x != nil {
		return x.Level
	}
	return LogLevel_LEVEL_UNSPECIFIED
}

type LogEntry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Seq                uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	TimestampUnixNanos int64                  `protobuf:"varint,2,opt,name=timestamp_unix_nanos,json=timestampUnixNanos,proto3" json:"timestamp_unix_nanos,omitempty"`
	Level              LogLevel_Level         `protobuf:"varint,3,opt,name=level,proto3,enum=bmc.v1.LogLevel_Level" json:"level,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *LogEntry) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogEntry) GetTimestampUnixNanos() int64 {
	if x != nil {
		return x.TimestampUnixNanos
	}
	return 0
}

func (x *LogEntry) GetLevel() LogLevel_Level {
	if x != nil {
		return x.Level
	}
	return LogLevel_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RunLogBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run_id非空表示运行日志；run_id为空表示Agent进程日志。
	// 复用现有包络以兼容未升级的Agent。
	RunId         string      `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Entries       []*LogEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunLogBatch) Reset() {
	*x = RunLogBatch{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLogBatch) ProtoMessage() {}

func (x *RunLogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLogBatch.ProtoReflect.Descriptor instead.
func (*RunLogBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RunLogBatch) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunLogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Terminal state of a run. Sent exactly once per run_id; re-sent verbatim when
// the server redelivers a command for an already-finished run (idempotency).
type RunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        RunResult_Status       `protobuf:"varint,2,opt,name=status,proto3,enum=bmc.v1.RunResult_Status" json:"status,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SnapshotIds   []string               `protobuf:"bytes,5,rep,name=snapshot_ids,json=snapshotIds,proto3" json:"snapshot_ids,omitempty"`
	ResultJson    string                 `protobuf:"bytes,6,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResult) Reset() {
	*x = RunResult{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResult) ProtoMessage() {}

func (x *RunResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResult.ProtoReflect.Descriptor instead.
func (*RunResult) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RunResult) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunResult) GetStatus() RunResult_Status {
	if x != nil {
		return x.Status
	}
	return RunResult_STATUS_UNSPECIFIED
}

func (x *RunResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RunResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RunResult) GetSnapshotIds() []string {
	if x != nil {
		return x.SnapshotIds
	}
	return nil
}

func (x *RunResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type ToolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ToolInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PathMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPath      string                 `protobuf:"bytes,1,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	RuntimePath   string                 `protobuf:"bytes,2,opt,name=runtime_path,json=runtimePath,proto3" json:"runtime_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathMapping) Reset() {
	*x = PathMapping{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathMapping) ProtoMessage() {}

func (x *PathMapping) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathMapping.ProtoReflect.Descriptor instead.
func (*PathMapping) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *PathMapping) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *PathMapping) GetRuntimePath() string {
	if x != nil {
		return x.RuntimePath
	}
	return ""
}

func (x *PathMapping) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type CapabilitiesReport struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Tools               []*ToolInfo            `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	SourcePathMappings  []*PathMapping         `protobuf:"bytes,2,rep,name=source_path_mappings,json=sourcePathMappings,proto3" json:"source_path_mappings,omitempty"`
	RestorePathMappings []*PathMapping         `protobuf:"bytes,3,rep,name=restore_path_mappings,json=restorePathMappings,proto3" json:"restore_path_mappings,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CapabilitiesReport) Reset() {
	*x = CapabilitiesReport{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesReport) ProtoMessage() {}

func (x *CapabilitiesReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesReport.ProtoReflect.Descriptor instead.
func (*CapabilitiesReport) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *CapabilitiesReport) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *CapabilitiesReport) GetSourcePathMappings() []*PathMapping {
	if x != nil {
		return x.SourcePathMappings
	}
	return nil
}

func (x *CapabilitiesReport) GetRestorePathMappings() []*PathMapping {
	if x != nil {
		return x.RestorePathMappings
	}
	return nil
}

type ExecuteCommand struct {
	state     protoimpl.MessageState   `protogen:"open.v1"`
	CommandId string                   `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	RunId     string                   `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Operation ExecuteCommand_Operation `protobuf:"varint,3,opt,name=operation,proto3,enum=bmc.v1.ExecuteCommand_Operation" json:"operation,omitempty"`
	// Structured task parameters shared as internal/model JSON payloads keyed by
	// operation. Never contains secrets.
	ParamsJson    []byte     `protobuf:"bytes,4,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	Secrets       *SecretSet `protobuf:"bytes,5,opt,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommand) Reset() {
	*x = ExecuteCommand{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommand) ProtoMessage() {}

func (x *ExecuteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommand.ProtoReflect.Descriptor instead.
func (*ExecuteCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ExecuteCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteCommand) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecuteCommand) GetOperation() ExecuteCommand_Operation {
	if x != nil {
		return x.Operation
	}
	return ExecuteCommand_OPERATION_UNSPECIFIED
}

func (x *ExecuteCommand) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *ExecuteCommand) GetSecrets() *SecretSet {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// Secrets travel only inside this message over mTLS, never in params_json.
type SecretSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full rclone.conf content for the repository's storage target.
	RcloneConf string `protobuf:"bytes,1,opt,name=rclone_conf,json=rcloneConf,proto3" json:"rclone_conf,omitempty"`
	// Restic repository password.
	ResticPassword string `protobuf:"bytes,2,opt,name=restic_password,json=resticPassword,proto3" json:"restic_password,omitempty"`
	// Database password for postgresql/mysql/mongodb plans.
	DbPassword    string `protobuf:"bytes,3,opt,name=db_password,json=dbPassword,proto3" json:"db_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretSet) Reset() {
	*x = SecretSet{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSet) ProtoMessage() {}

func (x *SecretSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSet.ProtoReflect.Descriptor instead.
func (*SecretSet) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *SecretSet) GetRcloneConf() string {
	if x != nil {
		return x.RcloneConf
	}
	return ""
}

func (x *SecretSet) GetResticPassword() string {
	if x != nil {
		return x.ResticPassword
	}
	return ""
}

func (x *SecretSet) GetDbPassword() string {
	if x != nil {
		return x.DbPassword
	}
	return ""
}

type CancelCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCommand) Reset() {
	*x = CancelCommand{}
	mi := &file_api_proto_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCommand) ProtoMessage() {}

func (x *CancelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCommand.ProtoReflect.Descriptor instead.
func (*CancelCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *CancelCommand) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

var File_api_proto_v1_agent_proto protoreflect.FileDescriptor

const file_api_proto_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/v1/agent.proto\x12\x06bmc.v1\"\xd4\x01\n" +
	"\rEnrollRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\fR\x06secret\x12&\n" +
	"\x0ftarget_agent_id\x18\a \x01(\tR\rtargetAgentId\"+\n" +
	"\x0eEnrollResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xd0\x03\n" +
	"\fAgentMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\r.bmc.v1.HelloH\x00R\x05hello\x121\n" +
	"\theartbeat\x18\v \x01(\v2\x11.bmc.v1.HeartbeatH\x00R\theartbeat\x12D\n" +
	"\x10command_accepted\x18\f \x01(\v2\x17.bmc.v1.CommandAcceptedH\x00R\x0fcommandAccepted\x128\n" +
	"\frun_progress\x18\r \x01(\v2\x13.bmc.v1.RunProgressH\x00R\vrunProgress\x129\n" +
	"\rrun_log_batch\x18\x0e \x01(\v2\x13.bmc.v1.RunLogBatchH\x00R\vrunLogBatch\x122\n" +
	"\n" +
	"run_result\x18\x0f \x01(\v2\x11.bmc.v1.RunResultH\x00R\trunResult\x12M\n" +
	"\x13capabilities_report\x18\x10 \x01(\v2\x1a.bmc.v1.CapabilitiesReportH\x00R\x12capabilitiesReportB\t\n" +
	"\apayload\"\xe9\x01\n" +
	"\rServerMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12+\n" +
	"\awelcome\x18\n" +
	" \x01(\v2\x0f.bmc.v1.WelcomeH\x00R\awelcome\x12A\n" +
	"\x0fexecute_command\x18\v \x01(\v2\x16.bmc.v1.ExecuteCommandH\x00R\x0eexecuteCommand\x12>\n" +
	"\x0ecancel_command\x18\f \x01(\v2\x15.bmc.v1.CancelCommandH\x00R\rcancelCommandB\t\n" +
	"\apayload\"a\n" +
	"\x05Hello\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xd2\x01\n" +
	"\aWelcome\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12,\n" +
	"\x12server_instance_id\x18\x02 \x01(\tR\x10serverInstanceId\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\x124\n" +
	"\x16version_minor_mismatch\x18\x04 \x01(\bR\x14versionMinorMismatch\"Q\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"unix_nanos\x18\x01 \x01(\x03R\tunixNanos\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x01R\ruptimeSeconds\"G\n" +
	"\x0fCommandAccepted\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"\xf5\x01\n" +
	"\vRunProgress\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\x12\x1d\n" +
	"\n" +
	"bytes_done\x18\x04 \x01(\x03R\tbytesDone\x12\x1f\n" +
	"\vbytes_total\x18\x05 \x01(\x03R\n" +
	"bytesTotal\x12\x1d\n" +
	"\n" +
	"files_done\x18\x06 \x01(\x03R\tfilesDone\x12\x1f\n" +
	"\vfiles_total\x18\a \x01(\x03R\n" +
	"filesTotal\x12\x1f\n" +
	"\vdetail_json\x18\b \x01(\tR\n" +
	"detailJson\"\x82\x01\n" +
	"\bLogLevel\x12,\n" +
	"\x05level\x18\x01 \x01(\x0e2\x16.bmc.v1.LogLevel.LevelR\x05level\"H\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\b\n" +
	"\x04WARN\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\"\x96\x01\n" +
	"\bLogEntry\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x120\n" +
	"\x14timestamp_unix_nanos\x18\x02 \x01(\x03R\x12timestampUnixNanos\x12,\n" +
	"\x05level\x18\x03 \x01(\x0e2\x16.bmc.v1.LogLevel.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"P\n" +
	"\vRunLogBatch\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12*\n" +
	"\aentries\x18\x02 \x03(\v2\x10.bmc.v1.LogEntryR\aentries\"\xa8\x02\n" +
	"\tRunResult\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.bmc.v1.RunResult.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12!\n" +
	"\fsnapshot_ids\x18\x05 \x03(\tR\vsnapshotIds\x12\x1f\n" +
	"\vresult_json\x18\x06 \x01(\tR\n" +
	"resultJson\"J\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSUCCEEDED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\"L\n" +
	"\bToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"j\n" +
	"\vPathMapping\x12\x1b\n" +
	"\thost_path\x18\x01 \x01(\tR\bhostPath\x12!\n" +
	"\fruntime_path\x18\x02 \x01(\tR\vruntimePath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\xcc\x01\n" +
	"\x12CapabilitiesReport\x12&\n" +
	"\x05tools\x18\x01 \x03(\v2\x10.bmc.v1.ToolInfoR\x05tools\x12E\n" +
	"\x14source_path_mappings\x18\x02 \x03(\v2\x13.bmc.v1.PathMappingR\x12sourcePathMappings\x12G\n" +
	"\x15restore_path_mappings\x18\x03 \x03(\v2\x13.bmc.v1.PathMappingR\x13restorePathMappings\"\xa9\x03\n" +
	"\x0eExecuteCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12>\n" +
	"\toperation\x18\x03 \x01(\x0e2 .bmc.v1.ExecuteCommand.OperationR\toperation\x12\x1f\n" +
	"\vparams_json\x18\x04 \x01(\fR\n" +
	"paramsJson\x12+\n" +
	"\asecrets\x18\x05 \x01(\v2\x11.bmc.v1.SecretSetR\asecrets\"\xd2\x01\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06BACKUP\x10\x01\x12\v\n" +
	"\aRESTORE\x10\x02\x12\x13\n" +
	"\x0fRESTORE_DRY_RUN\x10\x03\x12\t\n" +
	"\x05CHECK\x10\x04\x12\n" +
	"\n" +
	"\x06FORGET\x10\x05\x12\r\n" +
	"\tSNAPSHOTS\x10\x06\x12\x0f\n" +
	"\vSNAPSHOT_LS\x10\a\x12\x19\n" +
	"\x15VERIFY_STORAGE_REMOTE\x10\b\x12\x12\n" +
	"\x0eVALIDATE_PATHS\x10\t\x12\x16\n" +
	"\x12PROBE_CAPABILITIES\x10\n" +
	"\"v\n" +
	"\tSecretSet\x12\x1f\n" +
	"\vrclone_conf\x18\x01 \x01(\tR\n" +
	"rcloneConf\x12'\n" +
	"\x0frestic_password\x18\x02 \x01(\tR\x0eresticPassword\x12\x1f\n" +
	"\vdb_password\x18\x03 \x01(\tR\n" +
	"dbPassword\"&\n" +
	"\rCancelCommand\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId2\x83\x01\n" +
	"\fAgentControl\x127\n" +
	"\x06Enroll\x12\x15.bmc.v1.EnrollRequest\x1a\x16.bmc.v1.EnrollResponse\x12:\n" +
	"\aConnect\x12\x14.bmc.v1.AgentMessage\x1a\x15.bmc.v1.ServerMessage(\x010\x01B+Z)backupmanagementcenter/api/proto/v1;bmcv1b\x06proto3"

var (
	file_api_proto_v1_agent_proto_rawDescOnce sync.Once
	file_api_proto_v1_agent_proto_rawDescData []byte
)

func file_api_proto_v1_agent_proto_rawDescGZIP() []byte {
	file_api_proto_v1_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_agent_proto_rawDesc), len(file_api_proto_v1_agent_proto_rawDesc)))
	})
	return file_api_proto_v1_agent_proto_rawDescData
}

var file_api_proto_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_v1_agent_proto_goTypes = []any{
	(LogLevel_Level)(0),           // 0: bmc.v1.LogLevel.Level
	(RunResult_Status)(0),         // 1: bmc.v1.RunResult.Status
	(ExecuteCommand_Operation)(0), // 2: bmc.v1.ExecuteCommand.Operation
	(*EnrollRequest)(nil),         // 3: bmc.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 4: bmc.v1.EnrollResponse
	(*AgentMessage)(nil),          // 5: bmc.v1.AgentMessage
	(*ServerMessage)(nil),         // 6: bmc.v1.ServerMessage
	(*Hello)(nil),                 // 7: bmc.v1.Hello
	(*Welcome)(nil),               // 8: bmc.v1.Welcome
	(*Heartbeat)(nil),             // 9: bmc.v1.Heartbeat
	(*CommandAccepted)(nil),       // 10: bmc.v1.CommandAccepted
	(*RunProgress)(nil),           // 11: bmc.v1.RunProgress
	(*LogLevel)(nil),              // 12: bmc.v1.LogLevel
	(*LogEntry)(nil),              // 13: bmc.v1.LogEntry
	(*RunLogBatch)(nil),           // 14: bmc.v1.RunLogBatch
	(*RunResult)(nil),             // 15: bmc.v1.RunResult
	(*ToolInfo)(nil),              // 16: bmc.v1.ToolInfo
	(*PathMapping)(nil),           // 17: bmc.v1.PathMapping
	(*CapabilitiesReport)(nil),    // 18: bmc.v1.CapabilitiesReport
	(*ExecuteCommand)(nil),        // 19: bmc.v1.ExecuteCommand
	(*SecretSet)(nil),             // 20: bmc.v1.SecretSet
	(*CancelCommand)(nil),         // 21: bmc.v1.CancelCommand
}
var file_api_proto_v1_agent_proto_depIdxs = []int32{
	7,  // 0: bmc.v1.AgentMessage.hello:type_name -> bmc.v1.Hello
	9,  // 1: bmc.v1.AgentMessage.heartbeat:type_name -> bmc.v1.Heartbeat
	10, // 2: bmc.v1.AgentMessage.command_accepted:type_name -> bmc.v1.CommandAccepted
	11, // 3: bmc.v1.AgentMessage.run_progress:type_name -> bmc.v1.RunProgress
	14, // 4: bmc.v1.AgentMessage.run_log_batch:type_name -> bmc.v1.RunLogBatch
	15, // 5: bmc.v1.AgentMessage.run_result:type_name -> bmc.v1.RunResult
	18, // 6: bmc.v1.AgentMessage.capabilities_report:type_name -> bmc.v1.CapabilitiesReport
	8,  // 7: bmc.v1.ServerMessage.welcome:type_name -> bmc.v1.Welcome
	19, // 8: bmc.v1.ServerMessage.execute_command:type_name -> bmc.v1.ExecuteCommand
	21, // 9: bmc.v1.ServerMessage.cancel_command:type_name -> bmc.v1.CancelCommand
	0,  // 10: bmc.v1.LogLevel.level:type_name -> bmc.v1.LogLevel.Level
	0,  // 11: bmc.v1.LogEntry.level:type_name -> bmc.v1.LogLevel.Level
	13, // 12: bmc.v1.RunLogBatch.entries:type_name -> bmc.v1.LogEntry
	1,  // 13: bmc.v1.RunResult.status:type_name -> bmc.v1.RunResult.Status
	16, // 14: bmc.v1.CapabilitiesReport.tools:type_name -> bmc.v1.ToolInfo
	17, // 15: bmc.v1.CapabilitiesReport.source_path_mappings:type_name -> bmc.v1.PathMapping
	17, // 16: bmc.v1.CapabilitiesReport.restore_path_mappings:type_name -> bmc.v1.PathMapping
	2,  // 17: bmc.v1.ExecuteCommand.operation:type_name -> bmc.v1.ExecuteCommand.Operation
	20, // 18: bmc.v1.ExecuteCommand.secrets:type_name -> bmc.v1.SecretSet
	3,  // 19: bmc.v1.AgentControl.Enroll:input_type -> bmc.v1.EnrollRequest
	5,  // 20: bmc.v1.AgentControl.Connect:input_type -> bmc.v1.AgentMessage
	4,  // 21: bmc.v1.AgentControl.Enroll:output_type -> bmc.v1.EnrollResponse
	6,  // 22: bmc.v1.AgentControl.Connect:output_type -> bmc.v1.ServerMessage
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_proto_v1_agent_proto_init() }
func file_api_proto_v1_agent_proto_init() {
	if File_api_proto_v1_agent_proto != nil {
		return
	}
	file_api_proto_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_CommandAccepted)(nil),
		(*AgentMessage_RunProgress)(nil),
		(*AgentMessage_RunLogBatch)(nil),
		(*AgentMessage_RunResult)(nil),
		(*AgentMessage_CapabilitiesReport)(nil),
	}
	file_api_proto_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_Welcome)(nil),
		(*ServerMessage_ExecuteCommand)(nil),
		(*ServerMessage_CancelCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_agent_proto_rawDesc), len(file_api_proto_v1_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_agent_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_agent_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_agent_proto_msgTypes,
	}.Build()
	File_api_proto_v1_agent_proto = out.File
	file_api_proto_v1_agent_proto_goTypes = nil
	file_api_proto_v1_agent_proto_depIdxs = nil
}
